[web_service]
web1 ansible_connection=local
web2 ansible_connection=local
web3 ansible_connection=local


[db]
db1 ansible_connection=local
db2 ansible_connection=local
db3 ansible_connection=local

[all:vars]
ansible_become_password=1577890088
